SELECT USER FROM dual; 

SELECT * FROM EMPLOYEE ;

SELECT DEPTNO ,DEPTNAME ,FLOOR FROM DEPARTMENT ;

SELECT DEPTNO ,DEPTNAME ,FLOOR FROM DEPARTMENT WHERE DEPTNO = 1;

UPDATE DEPARTMENT 
 SET DEPTNAME = '마케팅2',FLOOR = 10
 WHERE DEPTNO = 5;

DELETE FROM DEPARTMENT 
WHERE DEPTNO = 5;
